# This rule is not used by the project labdns itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to labdns.shednet.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: labdns
    app.kubernetes.io/managed-by: kustomize
  name: dnsprovider-viewer-role
rules:
- apiGroups:
  - labdns.shednet.dev
  resources:
  - dnsproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - labdns.shednet.dev
  resources:
  - dnsproviders/status
  verbs:
  - get
