---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - labdns.shednet.dev
  resources:
  - dnsproviders
  verbs:
  - get
  - list
  - watch
